// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Tip: typeof import('./../src/components/tip.vue')['default']
    TodoCard: typeof import('./../src/components/todoCard.vue')['default']
    View: typeof import('./../src/components/view.vue')['default']
  }
}
